CREATE TABLE LOGIN_PRACTICE (
	ID VARCHAR(20) PRIMARY KEY
	, PW VARCHAR(20) NOT NULL
	, NICKNAME VARCHAR(20) UNIQUE NOT NULL
	, EMAIL VARCHAR(30) UNIQUE
	, BIRTHDAY DATE
	, HEIGHT INT
	, WEIGHT INT
	, GENDER VARCHAR(20)
	, TEL VARCHAR(20)
	, NATIONALITY VARCHAR(20)
	, JOIN_DATE DATETIME DEFAULT SYSDATE()
);

SELECT * FROM login_practice;

DROP TABLE login_practice;