CREATE TABLE practice(
	MEM_NUM INT PRIMARY KEY AUTO_INCREMENT
	, ID VARCHAR(20) NOT NULL UNIQUE
	, PW VARCHAR(20) NOT NULL
	, MEM_NAME VARCHAR(10) NOT NULL
	, MEM_AGE INT NOT NULL
	, MEM_TEL VARCHAR(20)
	, BIRTHDAY DATE
	, JOIN_DATE DATETIME DEFAULT SYSDATE()
	, COUNTRY VARCHAR(10)
	, GENDER VARCHAR(5) NOT NULL
);

SELECT * FROM practice;
DROP TABLE practice;
ROLLBACK;

INSERT INTO practice (
	ID
	, PW
	, MEM_NAME
	, MEM_AGE
	, MEM_TEL
	, BIRTHDAY
	, COUNTRY
	, GENDER
) VALUES (
	'id'
	, 'pw'
	, 'name'
	, 0
	, '01000000000'
	, '2000-01-01'
	, 'country'
	, 'gender'
);

ROLLBACK;

COMMIT;

SELECT IF(1 + 1 = 3, '정답', '오답');

SELE