#1.
CREATE TABLE BOOK_INFO (
	BOOK_NUM INT PRIMARY KEY,
	BOOK_NAME VARCHAR(20) NOT NULL,
	AUTHOR VARCHAR(20) NOT NULL,
	PRICE INT,
	PUBLISHER VARCHAR(20) DEFAULT '미지정',
	PUBLISH_DATE DATE
);

#2.
INSERT INTO BOOK_INFO (BOOK_NUM, BOOK_NAME, AUTHOR, PRICE, PUBLISHER, PUBLISH_DATE)
VALUES (101, '자바 기초', '홍길동', 30000, 'A출판', '2025-02-15');
INSERT INTO BOOK_INFO (BOOK_NUM, BOOK_NAME, AUTHOR, PRICE, PUBLISHER, PUBLISH_DATE)
VALUES (102, '리액트 기초', '이순신', 20000, 'B출판', '2025-01-22');

#3.
UPDATE BOOK_INFO
SET
	BOOK_NAME = '자바_고급',
	PRICE = 25000,
	PUBLISHER = 'IT출판'
WHERE BOOK_NUM = 101;

#4.
SELECT EMPNO, ENAME, SAL, COMM AS 인센티브
FROM emp
WHERE SAL BETWEEN 500 AND 3000
AND COMM IS NULL;

#5.
SELECT EMPNO, ENAME, JOB, HIREDATE
FROM emp
WHERE ENAME LIKE '%병%'
OR ENAME LIKE '%김%'
ORDER BY JOB ASC, EMPNO DESC;

#6.
SELECT EMPNO, ENAME, DEPTNO,
	CASE DEPTNO
		WHEN 10 THEN '인사부'
		WHEN 20 THEN '영업부'
		WHEN 30 THEN '개발부'
		ELSE '생산부' END
FROM emp;

#7.
SELECT EMPNO, ENAME, TO_CHAR(HIREDATE, 'YYYY.MM.DD HH24.MI.SS')
FROM emp
WHERE MONTH(HIREDATE) % 2 = 0
AND JOB IN ('사원', '과장', '차장')
ORDER BY HIREDATE ASC;

#8.
SELECT EMPNO, ENAME, SAL, COMM, SAL * 12 + COMM AS TOTAL_SALARY
FROM emp
WHERE IFNULL(COMM, 0)
ORDER BY SAL DESC;

#9.
SELECT EMPNO, DEPTNO, SUBSTR(ENAME, 2) AS 이름
FROM emp
WHERE YEAR(HIREDATE) >= 2003
AND YEAR(HIREDATE) <= 2006;

#10.
#3개






COMMIT;