CREATE TABLE member2 (
	ID VARCHAR(50) PRIMARY key
	, PW VARCHAR(50) NOT NULL
	, NAME VARCHAR(50) NOT NULL
);

SELECT * FROM member2;

SELECT * FROM board;

DESC board;

ALTER TABLE member2
ADD COLUMN ROLE VARCHAR(20) DEFAULT 'USER';

UPDATE member2
SET
	ROLE = 'ADMIN'
WHERE ID = 'admin';

COMMIT;

SELECT * FROM member2;

CREATE TABLE SECURITY_MEMBER (
	MEM_EMAIL VARCHAR(100) PRIMARY KEY
	, MEM_PW VARCHAR(100) NOT NULL
	, MEM_NAME VARCHAR(10) NOT NULL
	, MEM_ROLE VARCHAR(30) NOT NULL DEFAULT 'USER' # 'MANAGER', 'ADMIN'
);

SELECT * FROM security_member;