CREATE TABLE member2 (
	ID VARCHAR(50) PRIMARY key
	, PW VARCHAR(50) NOT NULL
	, NAME VARCHAR(50) NOT NULL
);

SELECT * FROM member2;

SELECT * FROM board;

DESC board;

ALTER TABLE member2
ADD COLUMN ROLE VARCHAR(20) DEFAULT 'USER';

UPDATE member2
SET
	ROLE = 'ADMIN'
WHERE ID = 'admin';

COMMIT;