#게시판 프로젝트 테이블
CREATE TABLE board (
	BOARD_NUM INT PRIMARY KEY AUTO_INCREMENT
	, TITLE VARCHAR(30) NOT NULL
	, WRITER VARCHAR(20) NOT NULL
	, CONTENT VARCHAR(50)
	, READ_CNT INT DEFAULT 0
	, CREATE_DATE DATETIME DEFAULT SYSDATE()
);

DELETE FROM board;

INSERT INTO board (
	TITLE
	, WRITER
	, CONTENT
) VALUES (
	'첫번째 글'
	, '김자바'
	, '첫 번째 게시글입니다.'
);

INSERT INTO board (
	TITLE
	, WRITER
	, CONTENT
) VALUES (
	'두번째 글'
	, '이자바'
	, '두 번째 게시글입니다.'
);

INSERT INTO board (
	TITLE
	, WRITER
	, CONTENT
) VALUES (
	'세번째 글'
	, '김자바'
	, '세 번째 게시글입니다.'
);

INSERT INTO board (
	TITLE
	, WRITER
	, CONTENT
) VALUES (
	'제목입니다'
	, '홍길동'
	, '내용입니다.'
);

INSERT INTO board (
	TITLE
	, WRITER
	, CONTENT
) VALUES (
	'안녕하세요'
	, '임꺽정'
	, '잘 부탁드립니다.'
);

DELETE FROM BOARD
WHERE BOARD_NUM = 35;

ROLLBACK;

COMMIT;

SELECT * FROM board;

DELETE FROM board
WHERE BOARD_NUM BETWEEN 8 AND 27;

#상품 정보 테이블
CREATE TABLE ITEM (
	ITEM_NUM INT PRIMARY KEY AUTO_INCREMENT
	, ITEM_CATEGORY VARCHAR(30) NOT NULL
	, ITEM_NAME VARCHAR(20) NOT NULL UNIQUE
	, ITEM_PRICE INT NOT NULL
	, ITEM_INTRO VARCHAR(50)
	, ITEM_STATUS VARCHAR(10) #상품준비중, 판매중, 매진
	, REG_DATE DATETIME DEFAULT SYSDATE()
);

INSERT INTO item (
	ITEM_CATEGORY
	, ITEM_NAME
	, ITEM_PRICE
) VALUES (
	'dfladjlfa'
	, 'askdjflad'
	, 123
);

SELECT
      ITEM_NUM
      , ITEM_CATEGORY
      , ITEM_NAME
      , ITEM_PRICE
      , ITEM_STATUS
      , TO_CHAR(REG_DATE, YYYY-MM-DD HH24:MI:SS)
    FROM ITEM
    ORDER BY REG_DATE DESC;
    
SELECT TO_CHAR('2025-01-01', 'YY-MM-DD');

DELETE FROM item;

COMMIT;

SELECT * FROM ITEM;

SELECT SUM(ITEM_PRICE) FROM item;

SELECT RANK(ITEM_PRICE, 2)
FROM item;

SELECT RANK();
SELECT SYSDATE();







#댓글 테이블
CREATE TABLE BOARD_REPLY (
	REPLY_NUM INT PRIMARY KEY AUTO_INCREMENT #댓글번호
	, CONTENT VARCHAR(30) NOT NULL #댓글내용
	, WRITER VARCHAR(20) NOT NULL #작성자
	, REG_DATE DATETIME DEFAULT SYSDATE() # 작성일
	, BOARD_NUM INT NOT NULL REFERENCES board (BOARD_NUM) #게시글번호
);

SELECT * FROM board_reply;