SELECT * FROM item_img;
SELECT * FROM item;
#신상품 조회
SELECT
	ITEM.ITEM_NUM
	, ITEM_NAME
	, PRICE
	, PART
	, ORIGIN
	, ATTACHED_IMG_NAME
	, IS_MAIN
FROM item INNER JOIN item_img IMG
ON item.ITEM_NUM = IMG.ITEM_NUM
WHERE IS_MAIN = 'Y'
ORDER BY REG_DATE DESC;

#하나의 상품 조회
SELECT
	ITEM.ITEM_NUM
	, ITEM_NAME
	, PRICE
	, PART
	, ORIGIN
	, ATTACHED_IMG_NAME
	, IS_MAIN
FROM item INNER JOIN item_img IMG
ON item.ITEM_NUM = IMG.ITEM_NUM
WHERE ITEM.ITEM_NUM = 11;

SELECT * FROM shop_cart;
SELECT PRICE FROM item;
SELECT * FROM item;
SELECT * FROM shop_member;

SELECT
  ITEM.ITEM_NUM
  , ITEM_NAME
  , PRICE
  , ATTACHED_IMG_NAME
  , (
		SELECT MEM_NAME
		FROM SHOP_MEMBER
		WHERE MEM_ROLE = 'ADMIN'
		AND MEM_ID = 'admin'
	) SELLER
FROM item INNER JOIN item_img IMG
ON item.ITEM_NUM = IMG.ITEM_NUM
WHERE IS_MAIN = 'Y'
ORDER BY REG_DATE DESC;

SELECT * FROM shop_cart;
SELECT * FROM shop_member;

SELECT MEM_ID
FROM SHOP_CART
WHERE ITEM_NUM = 19
AND MEM_ID = 'aaaaa';

SELECT
	CART_NUM
	, ITEM_NAME
	, CART_CNT
	, TOTAL_PRICE
	, CART_DATE
FROM shop_cart C
INNER JOIN item I
ON C.ITEM_NUM = I.ITEM_NUM
INNER JOIN shop_member M
ON M.MEM_ID = C.MEM_ID
WHERE M.MEM_ID = 'aaaaa';

SELECT * FROM shop_buy;

SELECT MEM_ROLE
FROM shop_member
WHERE MEM_ID = 'aaaaa';
SELECT * FROM qna;
