SELECT * FROM item_img;
SELECT * FROM item;
#신상품 조회
SELECT
	ITEM.ITEM_NUM
	, ITEM_NAME
	, PRICE
	, PART
	, ORIGIN
	, ATTACHED_IMG_NAME
	, IS_MAIN
FROM item INNER JOIN item_img IMG
ON item.ITEM_NUM = IMG.ITEM_NUM
WHERE IS_MAIN = 'Y'
ORDER BY REG_DATE DESC;

#하나의 상품 조회
SELECT
	ITEM.ITEM_NUM
	, ITEM_NAME
	, PRICE
	, PART
	, ORIGIN
	, ATTACHED_IMG_NAME
	, IS_MAIN
FROM item INNER JOIN item_img IMG
ON item.ITEM_NUM = IMG.ITEM_NUM
WHERE IS_MAIN = 'Y';