#학급 정보
CREATE TABLE class_info2 (
	CLASS_NUM INT PRIMARY KEY AUTO_INCREMENT
	, CLASS_NAME VARCHARACTER(50) NOT NULL
);

INSERT INTO class_info2 VALUES (1, '자바반');
INSERT INTO class_info2 VALUES (2, '영상반');
COMMIT;

CREATE TABLE STUDENT2 (
	STU_NUM INT PRIMARY KEY AUTO_INCREMENT
	, STU_NAME VARCHAR(50) NOT NULL
	, STU_AGE INT
	, CLASS_NUM INT NOT NULL REFERENCES class_info2 (CLASS_NUM)
);

INSERT INTO STUDENT2 VALUES (1, '김자바', 20, 1);
INSERT INTO STUDENT2 VALUES (2, '이자바', 30, 1);
INSERT INTO STUDENT2 VALUES (3, '박자바', 40, 1);

INSERT INTO STUDENT2 VALUES (4, '김영상', 20, 2);
INSERT INTO STUDENT2 VALUES (5, '이영상', 30, 2);
INSERT INTO STUDENT2 VALUES (6, '박영상', 40, 2);

COMMIT;