#1.
CREATE TABLE MY_MEMBER(
	MEMBER_NUM INT PRIMARY KEY,
	ID VARCHAR(20) NOT NULL,
	PW VARCHAR(20) NOT NULL,
	MEMBER_NAME VARCHAR(20) NOT NULL,
	AGE INT,
	EMAIL VARCHAR(30) UNIQUE
);

SELECT * FROM MY_MEMBER;
#2.
INSERT INTO MY_MEMBER (MEMBER_NUM, ID, PW, MEMBER_NAME, AGE, EMAIL)
VALUES (101, 'kim', 1234, '김자바', 30, 'kim@gmail.com');
INSERT INTO MY_MEMBER (MEMBER_NUM, ID, PW, MEMBER_NAME, AGE, EMAIL)
VALUES (102, 'hong', 5678, '홍자바', 25, 'hong@gmail.com');
#3.
UPDATE MY_MEMBER
SET
	MEMBER_NAME = '유관순',
	AGE = AGE + 5
WHERE MEMBER_NUM = 101;
ROLLBACK;

SELECT * FROM emp;
#4.
SELECT EMPNO, ENAME, SAL, COMM
FROM emp
WHERE SAL BETWEEN (500 AND 3000)
AND COMM IS NOT NULL;
#5.
SELECT EMPNO, ENAME, HIREDATE
FROM emp
WHERE ENAME LIKE '%기'
OR ENAME LIKE '%김%'
ORDER BY EMPNO DESC;