#1.
CREATE TABLE MY_MEMBER (
	MEMBER_NUM INT PRIMARY KEY,
	ID VARCHAR(20) NOT NULL,
	PW VARCHAR(20) NOT NULL,
	MEMBER_NAME VARCHAR(20) NOT NULL,
	AGE INT,
	EMAIL VARCHAR(30) UNIQUE
);

SELECT * FROM my_member;
#2.
INSERT INTO my_member (MEMBER_NUM, ID, PW, MEMBER_NAME, AGE, EMAIL)
VALUES (101, 'kim', '1234', '김자바', 30, 'kim@gmail.com');
INSERT INTO my_member (MEMBER_NUM, ID, PW, MEMBER_NAME, AGE, EMAIL)
VALUES (102, 'hong', '5678', '홍자바', 25, 'hong@gmail.com');
#3.
UPDATE my_member
SET
	MEMBER_NAME = '유관순',
	AGE = AGE + 5
WHERE MEMBER_NUM = 101;
#---------
SELECT * FROM emp;
#4.
SELECT EMPNO, ENAME, SAL, COMM
FROM emp
WHERE SAL BETWEEN 500 AND 3000
AND COMM IS NOT NULL;
#5.
SELECT EMPNO, ENAME, HIREDATE
FROM emp
WHERE ENAME LIKE '%기'
OR ENAME LIKE '%김%'
ORDER BY EMPNO DESC;
#6.
SELECT EMPNO, ENAME, DEPTNO,
CASE DEPTNO
	WHEN 10 THEN '인사부'
	WHEN 20 THEN '영업부'
	WHEN 30 THEN '개발부'
	ELSE '생산부' END AS DEPTNAME
FROM emp;
#7.
SELECT EMPNO, ENAME, HIREDATE, IFNULL(COMM, 0) AS COMM
FROM emp
WHERE MONTH(HIREDATE) = 1
ORDER BY COMM ASC;

