CREATE TABLE BASIC_BOARD (
	BOARD_NUM INT PRIMARY KEY AUTO_INCREMENT,
	TITLE VARCHAR(30),
	WRITER VARCHAR(20),
	CONTENT VARCHAR(50),
	READ_CNT INT DEFAULT 0,
	CREATE_DATE DATETIME DEFAULT SYSDATE()
);

SELECT * FROM basic_board;

INSERT INTO basic_board (TITLE, WRITER, CONTENT)
VALUES ('test1', 'writer', 'content');
INSERT INTO basic_board (TITLE, WRITER, CONTENT)
VALUES ('test2', 'writer2', 'content2');
INSERT INTO basic_board (TITLE, WRITER, CONTENT)
VALUES ('test3', 'writer3', 'content3');
UPDATE basic_board
SET READ_CNT = 5
WHERE BOARD_NUM = 3;