#차량 판매 정보 시스템

#자동차 정보
CREATE TABLE CAR_INFO (
	MODEL_NUM INT PRIMARY KEY AUTO_INCREMENT
	, MODEL_NAME VARCHAR(20) NOT NULL
	, PRICE INT NOT NULL
	, MANUFACTURER VARCHAR(20) NOT NULL
);

#자동차 판매 정보
CREATE TABLE SALES_INFO (
	SALES_NUM INT PRIMARY KEY AUTO_INCREMENT
	, BUYER_NAME VARCHAR(20) NOT NULL
	, BUYER_TEL VARCHAR(20)
	, COLOR VARCHAR(15) NOT NULL
	, SALE_DATE DATETIME DEFAULT SYSDATE()
	, MODEL_NUM INT REFERENCES car_info(MODEL_NUM)
);

SELECT * FROM car_info;
SELECT * FROM sales_info;

SELECT
	MODEL_NUM
	, MODEL_NAME
FROM car_info;